import * as v from "valibot";

export const labelSchema = v.object({
  id: v.string(),
  name: v.string(),
  color: v.string(),
  createdAt: v.date(),
  taskId: v.nullable(v.string()),
  workspaceId: v.nullable(v.string()),
});

export const projectSchema = v.object({
  id: v.string(),
  workspaceId: v.string(),
  slug: v.string(),
  icon: v.nullable(v.string()),
  name: v.string(),
  description: v.nullable(v.string()),
  createdAt: v.date(),
  isPublic: v.nullable(v.boolean()),
  archivedAt: v.nullable(v.date()),
  discipline: v.nullable(v.string()),
  utilityClient: v.nullable(v.string()),
  contractNumber: v.nullable(v.string()),
  workOrderNumber: v.nullable(v.string()),
  contractType: v.nullable(v.string()),
  voltageKv: v.nullable(v.string()),
  mobilizationDate: v.nullable(v.date()),
  energizationTargetDate: v.nullable(v.date()),
  substantialCompletionDate: v.nullable(v.date()),
});

export const circuitSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  designation: v.string(),
  name: v.nullable(v.string()),
  type: v.string(),
  voltageKv: v.nullable(v.string()),
  substationFrom: v.nullable(v.string()),
  substationTo: v.nullable(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
  assetCount: v.optional(v.number()),
});

export const gridAssetSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  circuitId: v.nullable(v.string()),
  parentGridAssetId: v.nullable(v.string()),
  assetType: v.string(),
  designation: v.string(),
  description: v.nullable(v.string()),
  sequence: v.nullable(v.number()),
  latitude: v.nullable(v.string()),
  longitude: v.nullable(v.string()),
  stationing: v.nullable(v.string()),
  voltageKv: v.nullable(v.string()),
  attributes: v.nullable(v.record(v.string(), v.unknown())),
  createdAt: v.date(),
  updatedAt: v.date(),
  circuitDesignation: v.optional(v.nullable(v.string())),
  taskCount: v.optional(v.number()),
  completedTaskCount: v.optional(v.number()),
  completionPercentage: v.optional(v.number()),
});

export const outageSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  circuitId: v.nullable(v.string()),
  outageNumber: v.nullable(v.string()),
  title: v.string(),
  type: v.string(),
  status: v.string(),
  requestedStart: v.nullable(v.date()),
  requestedEnd: v.nullable(v.date()),
  approvedStart: v.nullable(v.date()),
  approvedEnd: v.nullable(v.date()),
  actualStart: v.nullable(v.date()),
  actualEnd: v.nullable(v.date()),
  requestedById: v.nullable(v.string()),
  approvedBy: v.nullable(v.string()),
  notes: v.nullable(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
  circuitDesignation: v.optional(v.nullable(v.string())),
  gatedTaskCount: v.optional(v.number()),
});

export const permitSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  gridAssetId: v.nullable(v.string()),
  type: v.string(),
  permitNumber: v.nullable(v.string()),
  description: v.nullable(v.string()),
  issuingAuthority: v.nullable(v.string()),
  status: v.string(),
  appliedAt: v.nullable(v.date()),
  issuedAt: v.nullable(v.date()),
  expiresAt: v.nullable(v.date()),
  notes: v.nullable(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
  gridAssetDesignation: v.optional(v.nullable(v.string())),
});

export const inspectionSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  taskId: v.nullable(v.string()),
  gridAssetId: v.nullable(v.string()),
  type: v.string(),
  description: v.nullable(v.string()),
  isHoldPoint: v.boolean(),
  status: v.string(),
  scheduledFor: v.nullable(v.date()),
  performedAt: v.nullable(v.date()),
  inspectorName: v.nullable(v.string()),
  result: v.nullable(v.string()),
  readings: v.nullable(v.record(v.string(), v.unknown())),
  createdAt: v.date(),
  updatedAt: v.date(),
  gridAssetDesignation: v.optional(v.nullable(v.string())),
  taskTitle: v.optional(v.nullable(v.string())),
});

export const constructionUnitSchema = v.object({
  id: v.string(),
  workspaceId: v.string(),
  code: v.string(),
  description: v.string(),
  unitOfMeasure: v.string(),
  discipline: v.nullable(v.string()),
  installHours: v.nullable(v.string()),
  removeHours: v.nullable(v.string()),
  transferHours: v.nullable(v.string()),
  installPrice: v.nullable(v.string()),
  removePrice: v.nullable(v.string()),
  transferPrice: v.nullable(v.string()),
  isActive: v.boolean(),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const payItemSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  constructionUnitId: v.string(),
  gridAssetId: v.nullable(v.string()),
  action: v.string(),
  estimatedQuantity: v.string(),
  unitPrice: v.nullable(v.string()),
  standardHours: v.nullable(v.string()),
  notes: v.nullable(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
  code: v.optional(v.string()),
  description: v.optional(v.string()),
  unitOfMeasure: v.optional(v.string()),
  gridAssetDesignation: v.optional(v.nullable(v.string())),
  installedQuantity: v.optional(v.string()),
});

export const productionEntrySchema = v.object({
  id: v.string(),
  projectId: v.string(),
  payItemId: v.string(),
  dailyReportId: v.nullable(v.string()),
  crewId: v.nullable(v.string()),
  quantity: v.string(),
  entryDate: v.date(),
  enteredByUserId: v.nullable(v.string()),
  notes: v.nullable(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
  code: v.optional(v.string()),
  description: v.optional(v.string()),
  unitOfMeasure: v.optional(v.string()),
  action: v.optional(v.string()),
  crewName: v.optional(v.nullable(v.string())),
});

export const earnedValueSchema = v.object({
  items: v.array(
    v.object({
      payItemId: v.string(),
      action: v.string(),
      code: v.string(),
      description: v.string(),
      unitOfMeasure: v.string(),
      gridAssetDesignation: v.nullable(v.string()),
      estimatedQuantity: v.string(),
      unitPrice: v.string(),
      standardHours: v.string(),
      installedQuantity: v.string(),
      budgetValue: v.string(),
      budgetHours: v.string(),
      earnedValue: v.string(),
      earnedHours: v.string(),
      percentComplete: v.number(),
      remainingValue: v.number(),
    }),
  ),
  totals: v.object({
    budgetValue: v.number(),
    earnedValue: v.number(),
    remainingValue: v.number(),
    budgetHours: v.number(),
    earnedHours: v.number(),
    actualHours: v.number(),
    hoursVariance: v.number(),
    productivityFactor: v.nullable(v.number()),
    percentComplete: v.number(),
  }),
});

export const taskSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  position: v.nullable(v.number()),
  number: v.nullable(v.number()),
  userId: v.nullable(v.string()),
  title: v.string(),
  description: v.nullable(v.string()),
  status: v.string(),
  priority: v.picklist([
    "no-priority",
    "routine",
    "expedited",
    "urgent",
    "emergency",
  ] as const),
  startDate: v.optional(v.date()),
  dueDate: v.optional(v.date()),
  gridAssetId: v.nullable(v.string()),
  holdReason: v.nullable(v.string()),
  createdAt: v.date(),
});

export const activitySchema = v.object({
  id: v.string(),
  taskId: v.string(),
  type: v.picklist([
    "comment",
    "task",
    "status_changed",
    "priority_changed",
    "unassigned",
    "assignee_changed",
    "due_date_changed",
    "title_changed",
    "description_changed",
    "create",
  ] as const),
  createdAt: v.date(),
  userId: v.nullable(v.string()),
  content: v.nullable(v.string()),
  eventData: v.nullable(v.record(v.string(), v.unknown())),
  externalUserName: v.nullable(v.string()),
  externalUserAvatar: v.nullable(v.string()),
  externalSource: v.nullable(v.string()),
  externalUrl: v.nullable(v.string()),
});

export const timeEntrySchema = v.object({
  id: v.string(),
  taskId: v.string(),
  userId: v.nullable(v.string()),
  description: v.nullable(v.string()),
  startTime: v.date(),
  endTime: v.optional(v.date()),
  duration: v.nullable(v.number()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const notificationSchema = v.object({
  id: v.string(),
  userId: v.string(),
  title: v.nullable(v.string()),
  content: v.nullable(v.string()),
  type: v.picklist([
    "info",
    "task_created",
    "workspace_created",
    "task_status_changed",
    "task_assignee_changed",
    "time_entry_created",
    "due_date_reminder",
    "task_overdue",
    "task_mention",
    "task_comment",
  ] as const),
  eventData: v.nullable(v.record(v.string(), v.unknown())),
  isRead: v.optional(v.boolean()),
  resourceId: v.optional(v.string()),
  resourceType: v.optional(v.picklist(["task", "workspace"] as const)),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const notificationPreferenceWorkspaceRuleSchema = v.object({
  id: v.string(),
  workspaceId: v.string(),
  workspaceName: v.string(),
  isActive: v.boolean(),
  emailEnabled: v.boolean(),
  ntfyEnabled: v.boolean(),
  gotifyEnabled: v.boolean(),
  webhookEnabled: v.boolean(),
  projectMode: v.picklist(["all", "selected"] as const),
  selectedProjectIds: v.array(v.string()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const notificationPreferenceSchema = v.object({
  emailAddress: v.nullable(v.string()),
  emailEnabled: v.boolean(),
  ntfyEnabled: v.boolean(),
  ntfyConfigured: v.boolean(),
  ntfyServerUrl: v.nullable(v.string()),
  ntfyTopic: v.nullable(v.string()),
  ntfyTokenConfigured: v.boolean(),
  maskedNtfyToken: v.nullable(v.string()),
  gotifyEnabled: v.boolean(),
  gotifyConfigured: v.boolean(),
  gotifyServerUrl: v.nullable(v.string()),
  gotifyTokenConfigured: v.boolean(),
  maskedGotifyToken: v.nullable(v.string()),
  webhookEnabled: v.boolean(),
  webhookConfigured: v.boolean(),
  webhookUrl: v.nullable(v.string()),
  webhookSecretConfigured: v.boolean(),
  maskedWebhookSecret: v.nullable(v.string()),
  taskAssignmentEnabled: v.boolean(),
  taskCommentEnabled: v.boolean(),
  taskStatusChangeEnabled: v.boolean(),
  dueDateReminderEnabled: v.boolean(),
  dueDateReminderLeadTimeMinutes: v.number(),
  workspaces: v.array(notificationPreferenceWorkspaceRuleSchema),
  createdAt: v.nullable(v.date()),
  updatedAt: v.nullable(v.date()),
});

export const githubIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  repositoryOwner: v.string(),
  repositoryName: v.string(),
  installationId: v.nullable(v.number()),
  branchPattern: v.optional(v.string()),
  commentTaskLinkOnGitHubIssue: v.optional(v.boolean()),
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const giteaIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  baseUrl: v.string(),
  repositoryOwner: v.string(),
  repositoryName: v.string(),
  maskedAccessToken: v.string(),
  webhookUrl: v.optional(v.string()),
  webhookSecret: v.optional(v.string()),
  branchPattern: v.optional(v.string()),
  commentTaskLinkOnGiteaIssue: v.optional(v.boolean()),
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const integrationEventsSchema = v.object({
  taskCreated: v.boolean(),
  taskStatusChanged: v.boolean(),
  taskPriorityChanged: v.boolean(),
  taskTitleChanged: v.boolean(),
  taskDescriptionChanged: v.boolean(),
  taskCommentCreated: v.boolean(),
});

export const slackIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  channelName: v.nullable(v.string()),
  webhookConfigured: v.boolean(),
  maskedWebhookUrl: v.string(),
  events: integrationEventsSchema,
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const discordIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  channelName: v.nullable(v.string()),
  webhookConfigured: v.boolean(),
  maskedWebhookUrl: v.string(),
  events: integrationEventsSchema,
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const genericWebhookIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  webhookConfigured: v.boolean(),
  maskedWebhookUrl: v.nullable(v.string()),
  secretConfigured: v.boolean(),
  maskedSecret: v.nullable(v.string()),
  events: v.object({
    ...integrationEventsSchema.entries,
    taskDeleted: v.boolean(),
    taskMoved: v.boolean(),
    taskDueDateChanged: v.boolean(),
    taskAssigneeChanged: v.boolean(),
    taskUnassigned: v.boolean(),
    dueDateReminder: v.boolean(),
  }),
  dueDateReminderLeadTimeMinutes: v.number(),
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const telegramIntegrationSchema = v.object({
  id: v.string(),
  projectId: v.string(),
  chatId: v.string(),
  threadId: v.nullable(v.number()),
  chatLabel: v.nullable(v.string()),
  botTokenConfigured: v.boolean(),
  maskedBotToken: v.string(),
  events: integrationEventsSchema,
  isActive: v.nullable(v.boolean()),
  createdAt: v.date(),
  updatedAt: v.date(),
});

export const commentSchema = v.object({
  id: v.string(),
  taskId: v.string(),
  userId: v.string(),
  content: v.string(),
  createdAt: v.date(),
  updatedAt: v.date(),
  user: v.optional(
    v.object({
      name: v.string(),
      image: v.nullable(v.string()),
    }),
  ),
});

export const configSchema = v.object({
  disableRegistration: v.nullable(v.boolean()),
  disablePasswordRegistration: v.nullable(v.boolean()),
  disableEmailOtpSignIn: v.nullable(v.boolean()),
  isDemoMode: v.boolean(),
  hasSmtp: v.boolean(),
  hasGithubSignIn: v.nullable(v.boolean()),
  hasGoogleSignIn: v.nullable(v.boolean()),
  hasDiscordSignIn: v.nullable(v.boolean()),
  hasCustomOAuth: v.nullable(v.boolean()),
  hasGuestAccess: v.nullable(v.boolean()),
  disableLoginForm: v.nullable(v.boolean()),
  customOAuthAutoLogin: v.nullable(v.boolean()),
  customOAuthLogoutUrl: v.nullable(v.string()),
  billingEnabled: v.boolean(),
});
